@startuml
'https://plantuml.com/sequence-diagram
autonumber

title Registrar usuario y guardar pedido

actor Usuario
participant Registro as Signup                  #ffff99
participant "Confirmación" as Confirmation      #ffff99
participant "MiniStore\n(servlet)" as Servlet   #ff9999
participant UserHelper                          #ff9999
participant CartHelper                          #ff9999
participant Cart                                #99ff99
participant User                                #99ff99
participant Purchase                            #99ff99
participant DataBase                            #orange
participant UserDAO                             #orange
participant PurchaseDAO                         #orange
database "Base de datos" as Database            #orange

Usuario --> Signup: Introduce correo, contraseña,\ntipo y número de tarjeta\ndespués de rellenar el carrito
Signup -> Servlet: signup()
Servlet -> UserHelper: signup()
create User
UserHelper -->> User: <<create>>
return user
UserHelper -> DataBase: registerUser(user)
DataBase -> UserDAO: registerUser(user)
UserDAO -> Database: inserta en la base de datos
UserHelper <<-- DataBase: ok
UserHelper -> CartHelper: retrieveCart()
return cart
UserHelper -> Cart: getTotal()
return total
create Purchase
UserHelper -->> Purchase: <<create>>
return purchase
UserHelper -> DataBase: addPurchase(purchase)
DataBase -> PurchaseDAO: addPurchase(purchase)
PurchaseDAO -> Database: inserta la compra en la base de datos
UserHelper <<-- DataBase: ok
UserHelper -> Cart: clear()
UserHelper -> Servlet: changeView()
Servlet --> Confirmation: Cambiar la vista
Confirmation --> Usuario: Muestra el importe de la compra

@enduml